version: 2

# Docker image to use for setup
var_1: &docker_image circleci/node:12.0.0

# Cache key
var_2: &cache_key yarn-packages-{{ checksum "yarn.lock" }}

# Settings common to each job
var_3: &job_defaults
  working_directory: ~/repo
  docker:
    - image: *docker_image

# Job step for checking out the source code from GitHub. This also ensures that the source code
# is rebased on top of master.
var_4: &checkout_code
  checkout:
    # After checkout, rebase on top of master. By default, PRs are not rebased on top of master,
    # which we want. See https://discuss.circleci.com/t/1662
    post: git pull --ff-only origin "refs/pull/${CI_PULL_REQUEST//*pull\//}/merge"

# Restores the cache that could be available for the current lock file.
var_5: &restore_cache
  restore_cache:
    key: *cache_key

# Save cahce
var_6: &save_cache
  save_cache:
    key: *cache_key
    paths:
      - ~/.cache/yarn

var_7: &attach_workspace
  attach_workspace:
    at: .

# Ignore branches
var_9: &ignore_branch_filter
  branches:
    ignore:
      - "gh-pages"

jobs:
  prepare:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *restore_cache
      - run: yarn install --frozen-lockfile --non-interactive
      - *save_cache
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  build_package:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *attach_workspace
      - run: yarn build
      - store_artifacts:
          path: ./dist
      - *save_cache

  build_storybook:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *attach_workspace
      - run: yarn storybook:build
      - persist_to_workspace:
          root: .
          paths:
            - storybook-static

  test:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *attach_workspace
      - run: yarn test -- --runInBand --no-cache --coverage
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage

  chroma:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *attach_workspace
      - run: npx chroma publish

  publish_storybook:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *attach_workspace
      - run: yarn copy
      - run: yarn storybook:ci

  publish_dev_npm:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *attach_workspace
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: yarn publish:dev

  publish_prod_npm:
    <<: *job_defaults
    steps:
      - *checkout_code
      - *attach_workspace
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run: npm publish:tag

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - prepare:
          filters:
            branches:
              ignore:
                - "gh-pages"
      - build_package:
          requires:
            - prepare
      - build_storybook:
          requires:
            - prepare
      - test:
          requires:
            - build_storybook
            - build_package
      - chroma:
          requires:
            - build_storybook
            - build_package
            - test
      - publish_storybook:
          filters:
            branches:
              only:
                - master
          requires:
            - test
      - publish_dev_npm:
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/
          requires:
            - test
      - publish_prod_npm:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          requires:
            - test
